name:                brilhs
version:             0.1.0.0
github:              "saulecabrera/brilhs"
license:             BSD3
author:              "Saúl Cabrera"
maintainer:          "saulecabrera@gmail.com"
copyright:           "2021 Author name here"

extra-source-files:
- README.md
- ChangeLog.md

# Metadata used when publishing your package
# synopsis:            Short description of your package
# category:            Web

# To avoid duplicated efforts in documentation and dealing with the
# complications of embedding Haddock markup inside cabal files, it is
# common to point users to the README.md file.
description:         Please see the README on GitHub at <https://github.com/githubuser/brilhs#readme>

dependencies:
- base >= 4.7 && < 5
- text
- aeson
- unordered-containers
- scientific
- bytestring

library:
  source-dirs: src

executables:
  brilhs-exe:
    main:                Main.hs
    source-dirs:         app
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - brilhs

tests:
  brilhs-test:
    main:                Spec.hs
    source-dirs:         test
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - brilhs
