name: CI

on: [push, pull_request]

jobs:
  ci:
    name: CI
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: haskell/actions/setup@v1
        with:
          ghc-version: '8.10.7'
          enable-stack: true
          stack-version: 'latest'
      - uses: actions/setup-python@v2
        with:
            python-version: '3.x'
            architecture: x64

      - name: Ensure pip
        run: python3 -m ensurepip --upgrade

      - name: Install turnt
        run: python3 -m pip install --user turnt

      - name: Install flit
        run:  python3 -m pip install flit

      - name: Install bril tooling
        run: |
          git clone https://github.com/sampsyo/bril
          cd bril/bril-txt
          flit install --symlink --user

      - name: Install hspec-discover
        run: stack install hspec-discover

      - name: Install hlint
        run: stack install hlint

      - name: Lint
        run: hlint . 

      - name: Tests
        run: stack test

      - name: Turnt tests
        run: |
          cd test/integration/cfg
          turnt *.bril


